[0m16:36:15.978486 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b395690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3ad550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10b3add50>]}


============================== 16:36:15.993078 | 7352a451-b511-4f66-bebf-c1ccf5963026 ==============================
[0m16:36:15.993078 [info ] [MainThread]: Running with dbt=1.5.6
[0m16:36:15.994427 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/Elsbeth/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m16:36:15.996611 [debug] [MainThread]: Starter project path: /Users/Elsbeth/dbtcourse/venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m16:41:35.355500 [info ] [MainThread]: Profile dbtlearn written to /Users/Elsbeth/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m16:41:35.372963 [info ] [MainThread]: 
Your new dbt project "dbtlearn" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m16:41:35.384508 [debug] [MainThread]: Command `dbt init` succeeded at 16:41:35.381167 after 319.48 seconds
[0m16:41:35.388879 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e8df10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f07010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fef050>]}
[0m16:41:35.396771 [debug] [MainThread]: Flushing usage events
[0m17:38:55.005646 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11396bf90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113970410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113988ad0>]}


============================== 17:38:55.020334 | ac64f56c-093b-4aee-81f6-63b130191435 ==============================
[0m17:38:55.020334 [info ] [MainThread]: Running with dbt=1.5.6
[0m17:38:55.021919 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/Elsbeth/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m17:38:55.023036 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/Elsbeth/dbtcourse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:38:55.024780 [debug] [MainThread]: Command `dbt run` failed at 17:38:55.024334 after 0.13 seconds
[0m17:38:55.025530 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110567050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11395f1d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11395ef10>]}
[0m17:38:55.026119 [debug] [MainThread]: Flushing usage events
